name: DisplayChest
description: DisplayChest
main: com.connorlinfoot.displaychest.DisplayChest
version: 1.1-SNAPSHOT
commands:
  displaychest:
    description: Spawn in a display chest
permissions:
  displaychest.edit:
    default: op
  displaychest.view:
    default: true